[colors.primary]
background = "#221f1d"
foreground = "#e8e3d8"

[colors.cursor]
text = "#221f1d"
cursor = "#e8e3d8"

[colors.selection]
text = "#e8e3d8"
background = "#3c3836"

[colors.normal]
black   = "#221f1d"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4cdbf"

[colors.bright]
black   = "#6b6558"
red     = "#f2857e"
green   = "#bccb7f"
yellow  = "#e5bb76"
blue    = "#97c3b8"
magenta = "#dfa0b1"
cyan    = "#a0c79a"
white   = "#e8e3d8"
