[colors.primary]
background = "#0E1415"
foreground = "#DBCBA6"

[colors.cursor]
text = "#0E1415"
cursor = "#DBCBA6"

[colors.selection]
text = "#DBCBA6"
background = "#1C3D3A"

[colors.normal]
black   = "#0E1415"
red     = "#C85D60"
green   = "#82CE8A"
yellow  = "#75C7BD"
blue    = "#75C7BD"
magenta = "#7AACDB"
cyan    = "#3CA599"
white   = "#DBCBA6"

[colors.bright]
black   = "#5A6362"
red     = "#C85D60"
green   = "#3D9A48"
yellow  = "#75C7BD"
blue    = "#75C7BD"
magenta = "#7AACDB"
cyan    = "#3CA599"
white   = "#F0E6D2"
