[colors.primary]
background = "#0e1018"
foreground = "#ddd5c0"

[colors.cursor]
text = "#0e1018"
cursor = "#ddd5c0"

[colors.selection]
text = "#ddd5c0"
background = "#2d313d"

[colors.normal]
black   = "#2d313d"
red     = "#ea6962"
green   = "#a4cc6c"
yellow  = "#e9b949"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8bba7f"
white   = "#c9c1ad"

[colors.bright]
black   = "#81878f"
red     = "#f28379"
green   = "#b9da8e"
yellow  = "#f2cc6f"
blue    = "#9dbcb1"
magenta = "#e0a2b3"
cyan    = "#a3cc97"
white   = "#ddd5c0"
