[colors.primary]
background = "#072727"
foreground = "#d1b897"

[colors.cursor]
text = "#072727"
cursor = "#8cde94"

[colors.selection]
text = "#d1b897"
background = "#1a5053"

[colors.normal]
black   = "#072727"
red     = "#e05252"
green   = "#44b340"
yellow  = "#e6db74"
blue    = "#66d9ef"
magenta = "#ae81ff"
cyan    = "#2ec09c"
white   = "#d1b897"

[colors.bright]
black   = "#126367"
red     = "#f05f7a"
green   = "#6ad066"
yellow  = "#f0e896"
blue    = "#8ee3f5"
magenta = "#c5a3ff"
cyan    = "#7ad0c6"
white   = "#ffffff"
