[colors.primary]
background = "#092a25"
foreground = "#cdad8c"

[colors.cursor]
text = "#092a25"
cursor = "#90ee90"

[colors.selection]
text = "#cdad8c"
background = "#1a5053"

[colors.normal]
black   = "#092a25"
red     = "#e05252"
green   = "#3fdf1f"
yellow  = "#e6db74"
blue    = "#66d9ef"
magenta = "#ae81ff"
cyan    = "#0fdfaf"
white   = "#cdad8c"

[colors.bright]
black   = "#126367"
red     = "#f05f7a"
green   = "#90ee90"
yellow  = "#f0e896"
blue    = "#8ee3f5"
magenta = "#c5a3ff"
cyan    = "#7fffd4"
white   = "#ffffff"
