-- gruvbox.nvim's own groups (hard contrast) with this palette swapped in,
-- diffed against the shared engine so only the differences live here
return function(c)
  return {
    ["@attribute"] = { link = "PreProc" },
    ["@attribute.builtin"] = { fg = c.aqua },
    ["@character.special"] = { fg = c.purple },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@comment.note"] = { link = "SpecialComment" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@debug"] = { fg = c.red },
    ["@define"] = { link = "Define" },
    ["@diff.delta"] = { link = "diffChanged" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.plus"] = { link = "diffAdded" },
    ["@exception"] = { link = "Exception" },
    ["@field"] = { link = "Identifier" },
    ["@float"] = { link = "Float" },
    ["@function.builtin"] = { fg = c.aqua },
    ["@function.builtin.call"] = { },
    ["@function.call"] = { link = "Function" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.debug"] = { fg = c.red },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.storage"] = { fg = c.red },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { fg = c.yellow },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.modifier.java"] = { link = "@keyword.type.java" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.typemod.function.declaration"] = { },
    ["@lsp.typemod.function.defaultLibrary"] = { },
    ["@lsp.typemod.function.definition"] = { },
    ["@lsp.typemod.method.declaration"] = { },
    ["@lsp.typemod.method.defaultLibrary"] = { },
    ["@lsp.typemod.method.definition"] = { },
    ["@lsp.typemod.variable.defaultLibrary"] = { },
    ["@macro"] = { link = "Macro" },
    ["@markup"] = { fg = c.fg1 },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.italic"] = { link = "@text.emphasis" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.link.url"] = { },
    ["@markup.list"] = { link = "Delimiter" },
    ["@markup.list.checked"] = { fg = c.green },
    ["@markup.list.unchecked"] = { fg = c.gray },
    ["@markup.math"] = { link = "Special" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.strong"] = { },
    ["@method.call"] = { link = "Function" },
    ["@module.builtin"] = { fg = c.fg1 },
    ["@namespace"] = { fg = c.fg1 },
    ["@parameter"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@punctuation.special"] = { fg = c.fg4 },
    ["@storageclass"] = { fg = c.red },
    ["@string.escape"] = { fg = c.purple },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.special"] = { fg = c.purple },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@structure"] = { fg = c.yellow },
    ["@symbol"] = { link = "Identifier" },
    ["@tag"] = { fg = c.red },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.builtin"] = { fg = c.red },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = c.fg0, bg = c.red },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@text.emphasis"] = { },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.literal"] = { link = "String" },
    ["@text.math"] = { link = "Special" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { fg = c.purple },
    ["@text.reference"] = { link = "Constant" },
    ["@text.strike"] = { strikethrough = true },
    ["@text.strong"] = { },
    ["@text.todo.checked"] = { fg = c.green },
    ["@text.todo.unchecked"] = { fg = c.gray },
    ["@text.underline"] = { underline = true },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@variable.builtin"] = { fg = c.fg1 },
    ["@variable.member"] = { link = "Identifier" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@variable.parameter.builtin"] = { fg = c.fg1 },
    BlinkCmpKindClass = { fg = c.yellow },
    BlinkCmpKindColor = { fg = c.purple },
    BlinkCmpKindConstant = { fg = c.orange },
    BlinkCmpKindConstructor = { fg = c.yellow },
    BlinkCmpKindEnum = { fg = c.yellow },
    BlinkCmpKindEnumMember = { fg = c.aqua },
    BlinkCmpKindEvent = { fg = c.purple },
    BlinkCmpKindField = { fg = c.blue },
    BlinkCmpKindFile = { fg = c.blue },
    BlinkCmpKindFolder = { fg = c.blue },
    BlinkCmpKindFunction = { fg = c.blue },
    BlinkCmpKindInterface = { fg = c.yellow },
    BlinkCmpKindKeyword = { fg = c.purple },
    BlinkCmpKindMethod = { fg = c.blue },
    BlinkCmpKindModule = { fg = c.blue },
    BlinkCmpKindOperator = { fg = c.yellow },
    BlinkCmpKindProperty = { fg = c.blue },
    BlinkCmpKindReference = { fg = c.purple },
    BlinkCmpKindSnippet = { fg = c.green },
    BlinkCmpKindStruct = { fg = c.yellow },
    BlinkCmpKindText = { fg = c.orange },
    BlinkCmpKindTypeParameter = { fg = c.yellow },
    BlinkCmpKindUnit = { fg = c.blue },
    BlinkCmpKindValue = { fg = c.orange },
    BlinkCmpKindVariable = { fg = c.orange },
    BlinkCmpLabel = { fg = c.fg0 },
    BlinkCmpLabelDeprecated = { fg = c.fg1 },
    BlinkCmpLabelDescription = { fg = c.gray },
    BlinkCmpLabelDetail = { fg = c.gray },
    BlinkCmpLabelMatch = { fg = c.blue },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.orange },
    BlinkCmpSource = { fg = c.gray },
    BlinkIndentBlue = { fg = c.blue },
    BlinkIndentBlueUnderline = { sp = c.blue, underline = true },
    BlinkIndentCyan = { fg = c.aqua },
    BlinkIndentCyanUnderline = { sp = c.aqua, underline = true },
    BlinkIndentGreen = { fg = c.green },
    BlinkIndentGreenUnderline = { sp = c.green, underline = true },
    BlinkIndentOrange = { fg = c.orange },
    BlinkIndentOrangeUnderline = { sp = c.orange, underline = true },
    BlinkIndentRed = { fg = c.red },
    BlinkIndentRedUnderline = { sp = c.red, underline = true },
    BlinkIndentViolet = { fg = c.purple },
    BlinkIndentVioletUnderline = { sp = c.purple, underline = true },
    BlinkIndentYellow = { fg = c.yellow },
    BlinkIndentYellowUnderline = { sp = c.yellow, underline = true },
    BlinkPairsBlue = { fg = c.blue },
    BlinkPairsCyan = { fg = c.aqua },
    BlinkPairsGreen = { fg = c.green },
    BlinkPairsOrange = { fg = c.orange },
    BlinkPairsPurple = { fg = c.purple },
    BlinkPairsRed = { fg = c.red },
    BlinkPairsYellow = { fg = c.yellow },
    BufferLineBufferSelected = { fg = c.red, bg = c.bg0 },
    CarbonBrokenSymlink = { fg = c.red },
    CarbonDanger = { fg = c.red },
    CarbonExe = { fg = c.yellow },
    CarbonFile = { fg = c.fg1 },
    CarbonIndicator = { fg = c.gray },
    CarbonPending = { fg = c.yellow },
    CarbonSymlink = { fg = c.aqua },
    Character = { fg = c.purple },
    CmpItemAbbr = { fg = c.fg0 },
    CmpItemAbbrDeprecated = { fg = c.fg1 },
    CmpItemAbbrMatch = { fg = c.blue },
    CmpItemAbbrMatchFuzzy = { sp = c.blue, undercurl = true },
    CmpItemKindClass = { fg = c.yellow },
    CmpItemKindClassIcon = { link = "CmpItemKindClass" },
    CmpItemKindColor = { fg = c.purple },
    CmpItemKindColorIcon = { link = "CmpItemKindColor" },
    CmpItemKindConstant = { fg = c.orange },
    CmpItemKindConstantIcon = { link = "CmpItemKindConstant" },
    CmpItemKindConstructor = { fg = c.yellow },
    CmpItemKindConstructorIcon = { link = "CmpItemKindConstructor" },
    CmpItemKindEnum = { fg = c.yellow },
    CmpItemKindEnumIcon = { link = "CmpItemKindEnum" },
    CmpItemKindEnumMember = { fg = c.aqua },
    CmpItemKindEnumMemberIcon = { link = "CmpItemKindEnumMember" },
    CmpItemKindEvent = { fg = c.purple },
    CmpItemKindEventIcon = { link = "CmpItemKindEvent" },
    CmpItemKindField = { fg = c.blue },
    CmpItemKindFieldIcon = { link = "CmpItemKindField" },
    CmpItemKindFile = { fg = c.blue },
    CmpItemKindFileIcon = { link = "CmpItemKindFile" },
    CmpItemKindFolder = { fg = c.blue },
    CmpItemKindFolderIcon = { link = "CmpItemKindFolder" },
    CmpItemKindFunction = { fg = c.blue },
    CmpItemKindFunctionIcon = { link = "CmpItemKindFunction" },
    CmpItemKindInterface = { fg = c.yellow },
    CmpItemKindInterfaceIcon = { link = "CmpItemKindInterface" },
    CmpItemKindKeyword = { fg = c.purple },
    CmpItemKindKeywordIcon = { link = "CmpItemKindKeyword" },
    CmpItemKindMethod = { fg = c.blue },
    CmpItemKindMethodIcon = { link = "CmpItemKindMethod" },
    CmpItemKindModule = { fg = c.blue },
    CmpItemKindModuleIcon = { link = "CmpItemKindModule" },
    CmpItemKindOperator = { fg = c.yellow },
    CmpItemKindOperatorIcon = { link = "CmpItemKindOperator" },
    CmpItemKindProperty = { fg = c.blue },
    CmpItemKindPropertyIcon = { link = "CmpItemKindProperty" },
    CmpItemKindReference = { fg = c.purple },
    CmpItemKindReferenceIcon = { link = "CmpItemKindReference" },
    CmpItemKindSnippet = { fg = c.green },
    CmpItemKindSnippetIcon = { link = "CmpItemKindSnippet" },
    CmpItemKindStruct = { fg = c.yellow },
    CmpItemKindStructIcon = { link = "CmpItemKindStruct" },
    CmpItemKindText = { fg = c.orange },
    CmpItemKindTextIcon = { link = "CmpItemKindText" },
    CmpItemKindTypeParameter = { fg = c.yellow },
    CmpItemKindTypeParameterIcon = { link = "CmpItemKindTypeParameter" },
    CmpItemKindUnit = { fg = c.blue },
    CmpItemKindUnitIcon = { link = "CmpItemKindUnit" },
    CmpItemKindValue = { fg = c.orange },
    CmpItemKindValueIcon = { link = "CmpItemKindValue" },
    CmpItemKindVariable = { fg = c.orange },
    CmpItemKindVariableIcon = { link = "CmpItemKindVariable" },
    CmpItemMenu = { fg = c.gray },
    CocCodeLens = { fg = c.gray },
    CocDiagnosticsError = { fg = c.red },
    CocDiagnosticsHint = { fg = c.aqua },
    CocDiagnosticsInfo = { fg = c.blue },
    CocDiagnosticsWarning = { fg = c.orange },
    CocErrorFloat = { fg = c.red },
    CocErrorHighlight = { sp = c.red, undercurl = true },
    CocErrorSign = { fg = c.red, bg = c.bg0 },
    CocHintFloat = { fg = c.aqua },
    CocHintHighlight = { sp = c.aqua, undercurl = true },
    CocHintSign = { fg = c.aqua, bg = c.bg0 },
    CocInfoFloat = { fg = c.blue },
    CocInfoHighlight = { sp = c.blue, undercurl = true },
    CocInfoSign = { fg = c.blue, bg = c.bg0 },
    CocMenuSel = { link = "PmenuSel" },
    CocSearch = { fg = c.blue },
    CocSelectedText = { fg = c.red },
    CocWarningFloat = { fg = c.orange },
    CocWarningHighlight = { sp = c.orange, undercurl = true },
    CocWarningSign = { fg = c.orange, bg = c.bg0 },
    ColorColumn = { bg = c.bg1 },
    Conceal = { fg = c.blue },
    CurSearch = { link = "IncSearch" },
    Cursor = { reverse = true },
    CursorColumn = { link = "CursorLine" },
    CursorLine = { bg = c.bg1 },
    CursorLineNr = { fg = c.yellow, bg = c.bg1 },
    DapBreakpointSymbol = { fg = c.red, bg = c.bg1 },
    DapStoppedSymbol = { fg = c.green, bg = c.bg1 },
    DapUIBreakpointsCurrentLine = { fg = c.yellow },
    DapUIBreakpointsDisabledLine = { fg = c.gray },
    DapUIBreakpointsInfo = { fg = c.aqua },
    DapUIBreakpointsLine = { fg = c.yellow },
    DapUIBreakpointsPath = { fg = c.blue },
    DapUICurrentFrameName = { fg = c.purple },
    DapUIDecoration = { fg = c.purple },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatBorder = { fg = c.aqua },
    DapUILineNumber = { fg = c.yellow },
    DapUIModifiedValue = { fg = c.red },
    DapUIPlayPause = { fg = c.green, bg = c.bg1 },
    DapUIRestart = { fg = c.green, bg = c.bg1 },
    DapUIScope = { fg = c.blue },
    DapUISource = { fg = c.fg1 },
    DapUIStepBack = { fg = c.blue, bg = c.bg1 },
    DapUIStepInto = { fg = c.blue, bg = c.bg1 },
    DapUIStepOut = { fg = c.blue, bg = c.bg1 },
    DapUIStepOver = { fg = c.blue, bg = c.bg1 },
    DapUIStop = { fg = c.red, bg = c.bg1 },
    DapUIStoppedThread = { fg = c.blue },
    DapUIThread = { fg = c.blue },
    DapUIType = { fg = c.orange },
    DapUIUnavailable = { fg = c.gray },
    DapUIWatchesEmpty = { fg = c.gray },
    DapUIWatchesError = { fg = c.red },
    DapUIWatchesValue = { fg = c.yellow },
    DapUIWinSelect = { fg = c.yellow },
    DashboardCenter = { fg = c.yellow },
    DashboardFooter = { fg = c.purple, italic = true },
    DashboardHeader = { fg = c.aqua },
    DashboardShortCut = { fg = c.orange },
    Debug = { link = "Special" },
    Define = { fg = c.purple },
    DiagnosticDeprecated = { strikethrough = true },
    DiagnosticFloatingHint = { fg = c.aqua },
    DiagnosticFloatingInfo = { fg = c.blue },
    DiagnosticFloatingOk = { fg = c.green },
    DiagnosticFloatingWarn = { fg = c.orange },
    DiagnosticHint = { fg = c.aqua },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticOk = { fg = c.green },
    DiagnosticSignError = { fg = c.red, bg = c.bg0 },
    DiagnosticSignHint = { fg = c.aqua, bg = c.bg0 },
    DiagnosticSignInfo = { fg = c.blue, bg = c.bg0 },
    DiagnosticSignOk = { fg = c.green, bg = c.bg0 },
    DiagnosticSignWarn = { fg = c.yellow, bg = c.bg0 },
    DiagnosticUnderlineHint = { sp = c.aqua, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.green, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.yellow, undercurl = true },
    DiagnosticUnnecessary = { link = "Comment" },
    DiagnosticVirtualTextError = { fg = c.red },
    DiagnosticVirtualTextHint = { fg = c.aqua },
    DiagnosticVirtualTextInfo = { fg = c.blue },
    DiagnosticVirtualTextOk = { fg = c.green },
    DiagnosticVirtualTextWarn = { fg = c.yellow },
    DiagnosticWarn = { fg = c.yellow },
    DiffAdd = { bg = c.diff_green },
    DiffChange = { bg = c.diff_aqua },
    DiffDelete = { bg = c.diff_red },
    DiffText = { fg = c.bg0, bg = c.diff_blue },
    DiffviewFilePanelDeletions = { fg = c.red },
    DiffviewFilePanelInsertions = { fg = c.green },
    DiffviewStatusModified = { fg = c.green },
    Directory = { fg = c.green },
    DirvishArg = { fg = c.yellow },
    DirvishPathTail = { fg = c.aqua },
    Done = { fg = c.orange },
    EndOfBuffer = { link = "NonText" },
    Error = { fg = c.red, reverse = true },
    ErrorMsg = { fg = c.bg0, bg = c.red },
    FinderSeparator = { fg = c.aqua },
    FloatBorder = { link = "NormalFloat" },
    FloatTitle = { link = "Title" },
    FoldColumn = { fg = c.gray, bg = c.bg0 },
    Folded = { fg = c.gray, bg = c.bg1 },
    FzfLuaTitle = { fg = c.red },
    GitSignsChange = { fg = c.orange },
    Ignore = { link = "Normal" },
    IlluminatedWordRead = { link = "LspReferenceRead" },
    IlluminatedWordText = { link = "LspReferenceText" },
    IlluminatedWordWrite = { link = "LspReferenceWrite" },
    IncSearch = { fg = c.orange, bg = c.bg0, reverse = true },
    LspCodeLens = { fg = c.gray },
    LspInlayHint = { link = "Comment" },
    LspReferenceRead = { fg = c.yellow },
    LspReferenceTarget = { link = "Visual" },
    LspReferenceText = { fg = c.yellow },
    LspReferenceWrite = { fg = c.orange },
    LspSagaAutoPreview = { fg = c.orange },
    LspSagaCodeActionBorder = { fg = c.fg1 },
    LspSagaCodeActionContent = { fg = c.green },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaDefPreviewBorder = { fg = c.blue },
    LspSagaDiagnosticBorder = { fg = c.purple },
    LspSagaDiagnosticHeader = { fg = c.green },
    LspSagaDiagnosticSource = { fg = c.orange },
    LspSagaHoverBorder = { fg = c.orange },
    LspSagaLspFinderBorder = { fg = c.fg1 },
    LspSagaRenameBorder = { fg = c.blue },
    LspSagaSignatureHelpBorder = { fg = c.green },
    LspSignatureActiveParameter = { link = "Search" },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonHighlight = { fg = c.aqua },
    MasonHighlightBlock = { fg = c.bg0, bg = c.blue },
    MasonHighlightBlockBold = { fg = c.bg0, bg = c.blue },
    MasonHighlightBlockBoldSecondary = { fg = c.bg0, bg = c.yellow },
    MasonHighlightBlockSecondary = { fg = c.bg0, bg = c.yellow },
    MasonHighlightSecondary = { fg = c.yellow },
    MasonMutedBlock = { fg = c.bg0, bg = c.fg4 },
    MasonMutedBlockBold = { fg = c.bg0, bg = c.fg4 },
    MatchParen = { fg = c.orange },
    MiniAnimateCursor = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat = { fg = c.fg1, bg = c.bg1 },
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticFloatingHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
    MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
    MiniClueTitle = { link = "FloatTitle" },
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },
    MiniDepsChangeAdded = { fg = c.green },
    MiniDepsChangeRemoved = { fg = c.red },
    MiniDepsHint = { link = "DiagnosticHint" },
    MiniDepsInfo = { link = "DiagnosticInfo" },
    MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
    MiniDepsPlaceholder = { link = "Comment" },
    MiniDepsTitle = { link = "Title" },
    MiniDepsTitleError = { link = "DiffDelete" },
    MiniDepsTitleSame = { link = "DiffChange" },
    MiniDepsTitleUpdate = { link = "DiffAdd" },
    MiniDiffOverAdd = { link = "DiffAdd" },
    MiniDiffOverChange = { link = "DiffText" },
    MiniDiffOverContext = { link = "DiffChange" },
    MiniDiffOverDelete = { link = "DiffDelete" },
    MiniDiffSignAdd = { fg = c.green },
    MiniDiffSignChange = { fg = c.aqua },
    MiniDiffSignDelete = { fg = c.red },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
    MiniFilesCursorLine = { bg = c.bg2 },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { fg = c.fg1 },
    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesTitle = { link = "FloatTitle" },
    MiniFilesTitleFocused = { fg = c.orange },
    MiniHipatternsFixme = { fg = c.bg0, bg = c.red },
    MiniHipatternsHack = { fg = c.bg0, bg = c.yellow },
    MiniHipatternsNote = { fg = c.bg0, bg = c.blue },
    MiniHipatternsTodo = { fg = c.bg0, bg = c.aqua },
    MiniIconsAzure = { fg = c.blue },
    MiniIconsBlue = { fg = c.blue },
    MiniIconsCyan = { fg = c.aqua },
    MiniIconsGreen = { fg = c.green },
    MiniIconsGrey = { fg = c.fg0 },
    MiniIconsOrange = { fg = c.orange },
    MiniIconsPurple = { fg = c.purple },
    MiniIconsRed = { fg = c.red },
    MiniIconsYellow = { fg = c.yellow },
    MiniIndentscopeSymbol = { fg = c.gray },
    MiniIndentscopeSymbolOff = { fg = c.yellow },
    MiniJump = { sp = c.orange, undercurl = true },
    MiniJump2dDim = { fg = c.gray },
    MiniJump2dSpot = { fg = c.orange, nocombine = true },
    MiniJump2dSpotAhead = { fg = c.aqua, bg = c.bg0, nocombine = true },
    MiniJump2dSpotUnique = { fg = c.yellow, nocombine = true },
    MiniMapNormal = { link = "NormalFloat" },
    MiniMapSymbolCount = { link = "Special" },
    MiniMapSymbolLine = { link = "Title" },
    MiniMapSymbolView = { link = "Delimiter" },
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyTitle = { link = "FloatTitle" },
    MiniOperatorsExchangeFrom = { link = "IncSearch" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
    MiniPickBorderText = { link = "FloatTitle" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "MiniPickNormal" },
    MiniPickMatchCurrent = { bg = c.bg2 },
    MiniPickMatchMarked = { link = "Visual" },
    MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { fg = c.gray },
    MiniStarterHeader = { link = "Title" },
    MiniStarterInactive = { link = "Comment" },
    MiniStarterItem = { link = "Normal" },
    MiniStarterItemBullet = { link = "Delimiter" },
    MiniStarterItemPrefix = { link = "WarningMsg" },
    MiniStarterQuery = { link = "MoreMsg" },
    MiniStarterSection = { link = "Delimiter" },
    MiniStatuslineDevinfo = { link = "StatusLine" },
    MiniStatuslineFileinfo = { link = "StatusLine" },
    MiniStatuslineFilename = { link = "StatusLineNC" },
    MiniStatuslineInactive = { link = "StatusLineNC" },
    MiniStatuslineModeCommand = { fg = c.bg0, bg = c.yellow, nocombine = true },
    MiniStatuslineModeInsert = { fg = c.bg0, bg = c.blue, nocombine = true },
    MiniStatuslineModeNormal = { fg = c.bg0, bg = c.fg1, nocombine = true },
    MiniStatuslineModeOther = { fg = c.bg0, bg = c.aqua, nocombine = true },
    MiniStatuslineModeReplace = { fg = c.bg0, bg = c.red, nocombine = true },
    MiniStatuslineModeVisual = { fg = c.bg0, bg = c.green, nocombine = true },
    MiniSurround = { link = "IncSearch" },
    MiniTablineCurrent = { fg = c.green, bg = c.bg1 },
    MiniTablineFill = { link = "TabLineFill" },
    MiniTablineHidden = { fg = c.bg4, bg = c.bg1 },
    MiniTablineModifiedCurrent = { fg = c.bg1, bg = c.green },
    MiniTablineModifiedHidden = { fg = c.bg1, bg = c.bg4 },
    MiniTablineModifiedVisible = { fg = c.bg1, bg = c.fg1 },
    MiniTablineTabpagesection = { link = "Search" },
    MiniTablineVisible = { fg = c.fg1, bg = c.bg1 },
    MiniTestFail = { fg = c.red },
    MiniTestPass = { fg = c.green },
    MiniTrailspace = { bg = c.red },
    ModeMsg = { fg = c.yellow },
    MoreMsg = { fg = c.yellow },
    NERDTreeCWD = { fg = c.green },
    NERDTreeClosable = { fg = c.orange },
    NERDTreeDir = { fg = c.aqua },
    NERDTreeDirSlash = { fg = c.aqua },
    NERDTreeExecFile = { fg = c.yellow },
    NERDTreeFile = { fg = c.fg1 },
    NERDTreeHelp = { fg = c.fg1 },
    NERDTreeOpenable = { fg = c.orange },
    NERDTreeToggleOff = { fg = c.red },
    NERDTreeToggleOn = { fg = c.green },
    NERDTreeUp = { fg = c.gray },
    NavicIconsArray = { fg = c.orange },
    NavicIconsBoolean = { fg = c.orange },
    NavicIconsClass = { fg = c.yellow },
    NavicIconsConstant = { fg = c.orange },
    NavicIconsConstructor = { fg = c.blue },
    NavicIconsEnum = { fg = c.purple },
    NavicIconsEnumMember = { fg = c.yellow },
    NavicIconsEvent = { fg = c.yellow },
    NavicIconsField = { fg = c.purple },
    NavicIconsFile = { fg = c.blue },
    NavicIconsFunction = { fg = c.blue },
    NavicIconsInterface = { fg = c.green },
    NavicIconsKey = { fg = c.aqua },
    NavicIconsMethod = { fg = c.blue },
    NavicIconsModule = { fg = c.orange },
    NavicIconsNamespace = { fg = c.blue },
    NavicIconsNull = { fg = c.orange },
    NavicIconsNumber = { fg = c.orange },
    NavicIconsObject = { fg = c.orange },
    NavicIconsOperator = { fg = c.red },
    NavicIconsPackage = { fg = c.aqua },
    NavicIconsProperty = { fg = c.aqua },
    NavicIconsString = { fg = c.green },
    NavicIconsStruct = { fg = c.purple },
    NavicIconsTypeParameter = { fg = c.red },
    NavicIconsVariable = { fg = c.purple },
    NeoTreeDirectoryIcon = { fg = c.green },
    NeoTreeDirectoryName = { fg = c.green },
    NeoTreeFloatBorder = { fg = c.gray },
    NeoTreeRootName = { fg = c.aqua },
    NeoTreeTitleBar = { fg = c.fg1, bg = c.bg2 },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlineIconSearch = { link = "NoiceCmdlinePopupBorderSearch" },
    NoiceCmdlinePopupBorder = { fg = c.blue },
    NoiceCmdlinePopupBorderSearch = { fg = c.yellow },
    NoiceConfirmBorder = { link = "NoiceCmdlinePopupBorder" },
    NoiceCursor = { link = "TermCursor" },
    NonText = { fg = c.bg2 },
    NormalNC = { link = "Normal" },
    NotifyDEBUGBorder = { fg = c.blue },
    NotifyDEBUGIcon = { fg = c.blue },
    NotifyDEBUGTitle = { fg = c.blue },
    NotifyINFOBorder = { fg = c.aqua },
    NotifyINFOIcon = { fg = c.aqua },
    NotifyINFOTitle = { fg = c.aqua },
    NotifyTRACEBorder = { fg = c.green },
    NotifyTRACEIcon = { fg = c.green },
    NotifyTRACETitle = { fg = c.green },
    NotifyWARNBorder = { fg = c.yellow },
    NotifyWARNIcon = { fg = c.yellow },
    NotifyWARNTitle = { fg = c.yellow },
    NvimTreeExecFile = { fg = c.green },
    NvimTreeFolderIcon = { fg = c.blue },
    NvimTreeGitDirty = { fg = c.yellow },
    NvimTreeGitMerge = { fg = c.purple },
    NvimTreeGitNew = { fg = c.yellow },
    NvimTreeGitRenamed = { fg = c.purple },
    NvimTreeGitStaged = { fg = c.yellow },
    NvimTreeImageFile = { fg = c.purple },
    NvimTreeIndentMarker = { },
    NvimTreeOpenedFile = { },
    NvimTreeOpenedFolderName = { fg = c.red },
    NvimTreeRootFolder = { fg = c.purple },
    NvimTreeSpecialFile = { fg = c.yellow, underline = true },
    NvimTreeSymlink = { fg = c.aqua },
    NvimTreeWindowPicker = { bg = c.aqua },
    Pmenu = { fg = c.fg1, bg = c.bg2 },
    PmenuMatch = { },
    PmenuMatchSel = { },
    PmenuSbar = { bg = c.bg2 },
    PmenuSel = { fg = c.bg2, bg = c.blue },
    PmenuThumb = { bg = c.bg4 },
    PreCondit = { fg = c.aqua },
    PreProc = { fg = c.aqua },
    Question = { fg = c.orange },
    QuickFixLine = { fg = c.purple },
    RainbowDelimiterBlue = { fg = c.blue },
    RainbowDelimiterCyan = { fg = c.aqua },
    RainbowDelimiterGreen = { fg = c.green },
    RainbowDelimiterOrange = { fg = c.orange },
    RainbowDelimiterRed = { fg = c.red },
    RainbowDelimiterViolet = { fg = c.purple },
    RainbowDelimiterYellow = { fg = c.yellow },
    SagaShadow = { fg = c.bg0 },
    Search = { fg = c.yellow, bg = c.bg0, reverse = true },
    SignColumn = { bg = c.bg0 },
    SnacksPicker = { fg = c.fg1 },
    SnacksPickerBorder = { link = "SnacksPicker" },
    SnacksPickerDir = { fg = c.gray },
    SnacksPickerGitStatusUntracked = { fg = c.gray },
    SnacksPickerListCursorLine = { link = "CursorLine" },
    SnacksPickerMatch = { fg = c.orange },
    SnacksPickerPathHidden = { fg = c.gray },
    SnacksPickerPathIgnored = { fg = c.bg3 },
    SnacksPickerPrompt = { fg = c.red },
    SnacksPickerTitle = { link = "SnacksPicker" },
    SpecialChar = { link = "Special" },
    SpecialComment = { link = "Special" },
    SpecialKey = { fg = c.fg4 },
    SpellCap = { sp = c.blue, undercurl = true },
    SpellLocal = { sp = c.aqua, undercurl = true },
    SpellRare = { sp = c.purple, undercurl = true },
    StartifyBracket = { fg = c.fg3 },
    StartifyFile = { fg = c.fg1 },
    StartifyFooter = { fg = c.bg2 },
    StartifyHeader = { fg = c.orange },
    StartifyNumber = { fg = c.blue },
    StartifyPath = { fg = c.gray },
    StartifySection = { fg = c.yellow },
    StartifySelect = { link = "Title" },
    StartifySlash = { fg = c.gray },
    StartifySpecial = { fg = c.bg2 },
    StartifyVar = { link = "StartifyPath" },
    StatusLine = { fg = c.fg1, bg = c.bg2 },
    StatusLineNC = { fg = c.fg4, bg = c.bg1 },
    StorageClass = { fg = c.orange },
    Structure = { fg = c.aqua },
    TSRainbowBlue = { fg = c.blue },
    TSRainbowCyan = { fg = c.aqua },
    TSRainbowGreen = { fg = c.green },
    TSRainbowOrange = { fg = c.orange },
    TSRainbowRed = { fg = c.red },
    TSRainbowViolet = { fg = c.purple },
    TSRainbowYellow = { fg = c.yellow },
    TabLine = { link = "TabLineFill" },
    TabLineFill = { fg = c.bg4, bg = c.bg1 },
    TabLineSel = { fg = c.green, bg = c.bg1 },
    Tag = { link = "Special" },
    TargetWord = { fg = c.blue },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { fg = c.orange },
    TelescopeMultiSelection = { fg = c.gray },
    TelescopeNormal = { fg = c.fg1 },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopePreviewTitle = { fg = c.red },
    TelescopePrompt = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopePromptPrefix = { fg = c.red },
    TelescopePromptTitle = { fg = c.red },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopeResultsTitle = { fg = c.red },
    TelescopeSelection = { link = "CursorLine" },
    TelescopeSelectionCaret = { fg = c.red },
    TermCursor = { reverse = true },
    Title = { fg = c.green },
    Todo = { fg = c.bg0, bg = c.yellow },
    Underlined = { fg = c.blue, underline = true },
    VertSplit = { link = "WinSeparator" },
    Visual = { bg = c.bg3 },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = c.red },
    WhichKeyTitle = { link = "NormalFloat" },
    Whitespace = { fg = c.bg2 },
    WildMenu = { fg = c.blue, bg = c.bg2 },
    WinBar = { fg = c.fg4, bg = c.bg0 },
    WinBarNC = { fg = c.fg3, bg = c.bg1 },
    WinSeparator = { fg = c.bg3, bg = c.bg0 },
    cOperator = { fg = c.purple },
    cStructure = { fg = c.orange },
    clojureAnonArg = { fg = c.yellow },
    clojureCharacter = { fg = c.aqua },
    clojureCond = { fg = c.orange },
    clojureDefine = { fg = c.orange },
    clojureDeref = { fg = c.yellow },
    clojureException = { fg = c.red },
    clojureFunc = { fg = c.yellow },
    clojureKeyword = { fg = c.blue },
    clojureMacro = { fg = c.orange },
    clojureMeta = { fg = c.yellow },
    clojureParen = { fg = c.fg3 },
    clojureQuote = { fg = c.yellow },
    clojureRegexp = { fg = c.aqua },
    clojureRegexpCharClass = { fg = c.fg3 },
    clojureRegexpEscape = { fg = c.aqua },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureRepeat = { fg = c.yellow },
    clojureSpecial = { fg = c.orange },
    clojureStringEscape = { fg = c.aqua },
    clojureUnquote = { fg = c.yellow },
    clojureVariable = { fg = c.blue },
    coffeeBracket = { fg = c.orange },
    coffeeCurly = { fg = c.orange },
    coffeeExtendedOp = { fg = c.fg3 },
    coffeeParen = { fg = c.fg3 },
    coffeeSpecialOp = { fg = c.fg3 },
    cppOperator = { fg = c.purple },
    csBraces = { fg = c.fg1 },
    csEndColon = { fg = c.fg1 },
    csInterpolationAlignDel = { fg = c.aqua },
    csInterpolationDelimiter = { fg = c.fg3 },
    csInterpolationFormat = { fg = c.aqua },
    csInterpolationFormatDel = { fg = c.aqua },
    csLogicSymbols = { fg = c.fg1 },
    csOpSymbols = { fg = c.fg3 },
    csParens = { fg = c.fg3 },
    cssAnimationProp = { fg = c.aqua },
    cssBackgroundProp = { fg = c.aqua },
    cssBorderOutlineProp = { fg = c.aqua },
    cssBoxProp = { fg = c.aqua },
    cssBraces = { fg = c.blue },
    cssClassName = { fg = c.green },
    cssColor = { fg = c.blue },
    cssColorProp = { fg = c.aqua },
    cssDimensionProp = { fg = c.aqua },
    cssFlexibleBoxProp = { fg = c.aqua },
    cssFontDescriptorProp = { fg = c.aqua },
    cssFontProp = { fg = c.aqua },
    cssFunctionName = { fg = c.yellow },
    cssGeneratedContentProp = { fg = c.aqua },
    cssIdentifier = { fg = c.orange },
    cssImportant = { fg = c.green },
    cssListProp = { fg = c.aqua },
    cssMarginProp = { fg = c.aqua },
    cssPaddingProp = { fg = c.aqua },
    cssPositioningProp = { fg = c.yellow },
    cssPrintProp = { fg = c.aqua },
    cssRenderProp = { fg = c.aqua },
    cssSelectorOp = { fg = c.blue },
    cssSelectorOp2 = { fg = c.blue },
    cssTableProp = { fg = c.aqua },
    cssTextProp = { fg = c.aqua },
    cssTransformProp = { fg = c.aqua },
    cssTransitionProp = { fg = c.aqua },
    cssUIProp = { fg = c.yellow },
    cssVendor = { fg = c.fg1 },
    debugBreakpoint = { fg = c.red, bg = c.bg0 },
    debugPC = { link = "DiffAdd" },
    diffAdded = { link = "DiffAdd" },
    diffChanged = { link = "DiffChange" },
    diffFile = { fg = c.orange },
    diffIndexLine = { link = "diffChanged" },
    diffLine = { fg = c.blue },
    diffNewFile = { fg = c.yellow },
    diffOldFile = { fg = c.orange },
    diffRemoved = { link = "DiffDelete" },
    docbkKeyword = { fg = c.aqua },
    dtdFunction = { fg = c.gray },
    dtdParamEntityDPunct = { fg = c.gray },
    dtdParamEntityPunct = { fg = c.gray },
    dtdTagName = { fg = c.purple },
    elixirDocString = { link = "Comment" },
    elixirInterpolationDelimiter = { fg = c.aqua },
    elixirModuleDeclaration = { fg = c.yellow },
    elixirStringDelimiter = { fg = c.green },
    gitcommitDiscardedFile = { fg = c.red },
    gitcommitSelectedFile = { fg = c.green },
    goBuiltins = { fg = c.orange },
    goConstants = { fg = c.purple },
    goDeclType = { fg = c.blue },
    goDeclaration = { fg = c.red },
    goDirective = { fg = c.aqua },
    haskellAssocType = { fg = c.aqua },
    haskellBacktick = { fg = c.orange },
    haskellBottom = { fg = c.red },
    haskellConditional = { fg = c.purple },
    haskellDecl = { fg = c.orange },
    haskellDeclKeyword = { fg = c.orange },
    haskellDefault = { fg = c.red },
    haskellDelimiter = { fg = c.orange },
    haskellDeriving = { fg = c.purple },
    haskellFloat = { fg = c.aqua },
    haskellForeignKeywords = { fg = c.green },
    haskellIdentifier = { fg = c.aqua },
    haskellImportKeywords = { fg = c.purple },
    haskellInfix = { fg = c.purple },
    haskellKeyword = { fg = c.red },
    haskellLet = { fg = c.red },
    haskellLiquid = { fg = c.purple },
    haskellNumber = { fg = c.aqua },
    haskellOperators = { fg = c.purple },
    haskellPatternKeyword = { fg = c.blue },
    haskellPragma = { fg = c.red },
    haskellPreProc = { fg = c.fg4 },
    haskellQuasiQuoted = { fg = c.blue },
    haskellQuote = { fg = c.green },
    haskellQuotedType = { fg = c.red },
    haskellRecursiveDo = { fg = c.purple },
    haskellSeparator = { fg = c.fg4 },
    haskellShebang = { fg = c.yellow },
    haskellStatement = { fg = c.purple },
    haskellTH = { fg = c.aqua },
    haskellType = { fg = c.blue },
    haskellTypeForall = { fg = c.red },
    haskellTypeRoles = { fg = c.red },
    haskellWhere = { fg = c.red },
    htmlArg = { fg = c.orange },
    htmlBold = { fg = c.fg0, bg = c.bg0 },
    htmlBoldItalic = { fg = c.fg0, bg = c.bg0, italic = true },
    htmlBoldUnderline = { fg = c.fg0, bg = c.bg0, underline = true },
    htmlBoldUnderlineItalic = { fg = c.fg0, bg = c.bg0, italic = true, underline = true },
    htmlEndTag = { fg = c.aqua },
    htmlItalic = { fg = c.fg0, bg = c.bg0, italic = true },
    htmlLink = { fg = c.fg4, underline = true },
    htmlSpecialChar = { fg = c.red },
    htmlSpecialTagName = { fg = c.blue },
    htmlTag = { fg = c.aqua },
    htmlTagN = { fg = c.fg1 },
    htmlTagName = { fg = c.blue },
    htmlUnderline = { fg = c.fg0, bg = c.bg0, underline = true },
    htmlUnderlineItalic = { fg = c.fg0, bg = c.bg0, italic = true, underline = true },
    iCursor = { link = "Cursor" },
    javaAnnotation = { fg = c.blue },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaDocTags = { fg = c.aqua },
    javaOperator = { fg = c.orange },
    javaParen = { fg = c.fg3 },
    javaParen1 = { fg = c.fg3 },
    javaParen2 = { fg = c.fg3 },
    javaParen3 = { fg = c.fg3 },
    javaParen4 = { fg = c.fg3 },
    javaParen5 = { fg = c.fg3 },
    javaScriptBraces = { fg = c.fg1 },
    javaScriptFunction = { fg = c.aqua },
    javaScriptIdentifier = { fg = c.red },
    javaScriptMember = { fg = c.blue },
    javaScriptNull = { fg = c.purple },
    javaScriptNumber = { fg = c.purple },
    javaScriptParens = { fg = c.fg3 },
    javaVarArg = { fg = c.green },
    jsonBraces = { fg = c.fg1 },
    jsonKeyword = { fg = c.green },
    jsonQuote = { fg = c.green },
    jsonString = { fg = c.fg1 },
    lCursor = { link = "Cursor" },
    luaFunction = { fg = c.aqua },
    luaIn = { fg = c.red },
    luaTable = { fg = c.orange },
    mailQuoted1 = { fg = c.aqua },
    mailQuoted2 = { fg = c.purple },
    mailQuoted3 = { fg = c.yellow },
    mailQuoted4 = { fg = c.green },
    mailQuoted5 = { fg = c.red },
    mailQuoted6 = { fg = c.orange },
    mailSignature = { link = "Comment" },
    markdownBlockquote = { fg = c.gray },
    markdownBold = { fg = c.fg3 },
    markdownBoldItalic = { fg = c.fg3, italic = true },
    markdownCode = { fg = c.aqua },
    markdownCodeBlock = { fg = c.aqua },
    markdownCodeDelimiter = { fg = c.aqua },
    markdownH1 = { fg = c.green },
    markdownH2 = { fg = c.green },
    markdownH3 = { fg = c.yellow },
    markdownH4 = { fg = c.yellow },
    markdownH5 = { fg = c.yellow },
    markdownH6 = { fg = c.yellow },
    markdownHeadingDelimiter = { fg = c.orange },
    markdownHeadingRule = { fg = c.gray },
    markdownIdDeclaration = { link = "markdownLinkText" },
    markdownItalic = { fg = c.fg3, italic = true },
    markdownLinkDelimiter = { fg = c.fg3 },
    markdownLinkText = { fg = c.gray, underline = true },
    markdownLinkTextDelimiter = { fg = c.fg3 },
    markdownListMarker = { fg = c.gray },
    markdownOrderedListMarker = { fg = c.gray },
    markdownRule = { fg = c.gray },
    markdownUrl = { fg = c.purple },
    markdownUrlDelimiter = { fg = c.fg3 },
    markdownUrlTitleDelimiter = { fg = c.green },
    moonExtendedOp = { fg = c.fg3 },
    moonFunction = { fg = c.fg3 },
    moonObject = { fg = c.yellow },
    moonSpecialOp = { fg = c.fg3 },
    netrwClassify = { fg = c.aqua },
    netrwCmdSep = { fg = c.fg3 },
    netrwComment = { fg = c.gray },
    netrwDir = { fg = c.aqua },
    netrwExe = { fg = c.yellow },
    netrwHelpCmd = { fg = c.aqua },
    netrwLink = { fg = c.gray },
    netrwList = { fg = c.blue },
    netrwSymLink = { fg = c.fg1 },
    netrwVersion = { fg = c.green },
    objcDirective = { fg = c.blue },
    objcTypeModifier = { fg = c.red },
    ocamlArrow = { fg = c.orange },
    ocamlConstructor = { fg = c.orange },
    ocamlInfixOpKeyword = { fg = c.red },
    ocamlKeyChar = { fg = c.orange },
    ocamlOperator = { fg = c.fg1 },
    purescriptAsKeyword = { fg = c.aqua },
    purescriptBacktick = { fg = c.orange },
    purescriptConditional = { fg = c.orange },
    purescriptConstructor = { fg = c.fg1 },
    purescriptDelimiter = { fg = c.fg4 },
    purescriptFunction = { fg = c.fg1 },
    purescriptHidingKeyword = { fg = c.aqua },
    purescriptImportKeyword = { fg = c.aqua },
    purescriptModuleKeyword = { fg = c.aqua },
    purescriptModuleName = { fg = c.fg1 },
    purescriptOperator = { fg = c.blue },
    purescriptStructure = { fg = c.aqua },
    purescriptType = { fg = c.fg1 },
    purescriptTypeVar = { fg = c.fg1 },
    purescriptWhere = { fg = c.aqua },
    pythonBoolean = { fg = c.purple },
    pythonBuiltin = { fg = c.orange },
    pythonBuiltinFunc = { fg = c.orange },
    pythonBuiltinObj = { fg = c.orange },
    pythonCoding = { fg = c.blue },
    pythonConditional = { fg = c.red },
    pythonDecorator = { fg = c.red },
    pythonDot = { fg = c.fg3 },
    pythonDottedName = { fg = c.green },
    pythonException = { fg = c.red },
    pythonExceptions = { fg = c.purple },
    pythonFunction = { fg = c.aqua },
    pythonImport = { fg = c.blue },
    pythonInclude = { fg = c.blue },
    pythonOperator = { fg = c.red },
    pythonRepeat = { fg = c.red },
    pythonRun = { fg = c.blue },
    rubyDefinedOperator = { link = "rubyKeyword" },
    rubyInterpolationDelimiter = { fg = c.aqua },
    rubyStringDelimiter = { fg = c.green },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { fg = c.aqua },
    rustEnum = { fg = c.aqua },
    rustEscape = { fg = c.aqua },
    rustModPathSep = { fg = c.fg2 },
    rustSigil = { fg = c.orange },
    rustStringContinuation = { fg = c.aqua },
    rustStructure = { fg = c.aqua },
    scalaCapitalWord = { fg = c.fg1 },
    scalaCaseFollowing = { fg = c.fg1 },
    scalaInstanceDeclaration = { fg = c.fg1 },
    scalaInterpolation = { fg = c.aqua },
    scalaKeyword = { fg = c.red },
    scalaKeywordModifier = { fg = c.red },
    scalaNameDefinition = { fg = c.fg1 },
    scalaOperator = { fg = c.fg1 },
    scalaSpecial = { fg = c.aqua },
    scalaTypeDeclaration = { fg = c.yellow },
    scalaTypeExtension = { fg = c.fg1 },
    scalaTypeTypePostDeclaration = { fg = c.yellow },
    typescriptAjaxMethods = { fg = c.fg1 },
    typescriptBraces = { fg = c.fg1 },
    typescriptDOMObjects = { fg = c.fg1 },
    typescriptDocParam = { link = "Comment" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptEndColons = { fg = c.fg1 },
    typescriptFuncKeyword = { fg = c.aqua },
    typescriptGlobalObjects = { fg = c.fg1 },
    typescriptHtmlElemProperties = { fg = c.fg1 },
    typescriptIdentifier = { fg = c.orange },
    typescriptInterpolationDelimiter = { fg = c.aqua },
    typescriptLabel = { fg = c.aqua },
    typescriptLogicSymbols = { fg = c.fg1 },
    typescriptNull = { fg = c.purple },
    typescriptOpSymbols = { fg = c.fg3 },
    typescriptParens = { fg = c.fg3 },
    typescriptReserved = { fg = c.aqua },
    vCursor = { link = "Cursor" },
    xmlAttrib = { fg = c.orange },
    xmlAttribPunct = { fg = c.gray },
    xmlCdataCdata = { fg = c.purple },
    xmlCdataStart = { fg = c.gray },
    xmlDocTypeDecl = { fg = c.gray },
    xmlDocTypeKeyword = { fg = c.purple },
    xmlEndTag = { fg = c.aqua },
    xmlEntity = { fg = c.red },
    xmlEntityPunct = { fg = c.red },
    xmlEqual = { fg = c.blue },
    xmlProcessingDelim = { fg = c.gray },
    xmlTag = { fg = c.aqua },
    xmlTagName = { fg = c.blue },
  }
end
